### ISSUE TITLE
File indexing crashes if file is missing in Moodle filedir

### ISSUE THREAD

**Issue by abias** [catalyst/moodle-search_elastic#29] opened 2017-08-11 21:34 UTC
Hi Matt,

I am currently looking into search_elastic and have added the latest version of this plugin to a Moodle 3.2.3+ (Build: 20170622) instance and have hooked this up to a fresh elasticsearch 5.5 instance.

I also started a standalone tika instance running on a separate machine and configured this tika instance in the plugin's settings.

While doing the first indexing with
`sudo -u apache /opt/rh/rh-php70/root/usr/bin/php /var/www/html/moodle_dev3/search/cli/indexer.php --force
`
with fileindexing enabled, the indexer script encountered a fatal error and stopped with this message:

```
////Default exception handler: Die Datei kann nicht gelesen werden. Eventuell existiert sie nicht oder es gibt ein Rechteproblem. Debug: [dataroot]/filedir/c2/40/c24091a092e5afc7310088ce2e416d1d7efcda11
Error code: storedfilecannotread
* line 579 of /lib/filestorage/stored_file.php: file_exception thrown
* line 274 of /search/engine/elastic/classes/document.php: call to stored_file->get_imageinfo()
* line 353 of /search/engine/elastic/classes/engine.php: call to search_elastic\document->export_file_for_engine()
* line 511 of /search/engine/elastic/classes/engine.php: call to search_elastic\engine->process_document_files()
* line 588 of /search/classes/manager.php: call to search_elastic\engine->add_document()
* line 75 of /search/cli/indexer.php: call to core_search\manager->index()

!!! Die Datei kann nicht gelesen werden. Eventuell existiert sie nicht oder es gibt ein Rechteproblem. !!!
!! [dataroot]/filedir/c2/40/c24091a092e5afc7310088ce2e416d1d7efcda11
Error code: storedfilecannotread !!
!! Stack trace: * line 579 of /lib/filestorage/stored_file.php: file_exception thrown
* line 274 of /search/engine/elastic/classes/document.php: call to stored_file-&gt;get_imageinfo()
* line 353 of /search/engine/elastic/classes/engine.php: call to search_elastic\document-&gt;export_file_for_engine()
* line 511 of /search/engine/elastic/classes/engine.php: call to search_elastic\engine-&gt;process_document_files()
* line 588 of /search/classes/manager.php: call to search_elastic\engine-&gt;add_document()
* line 75 of /search/cli/indexer.php: call to core_search\manager-&gt;index()
 !!

```

The german sentences in the debug message mean that the file couldn't be read from disk. This conclusion is correct as I ran the indexing on a Moodle test instance which was rsynced from our production system with excluding big files in Moodledata (almost always videos) for storage saving reasons. Unfortunately, due to this fact, I am unable to test indexing properly on this test instance.

Would it be possible to check if a file really exists on disk before it is sent to the file indexing backend and ignore it otherwise?

Thanks,
Alex

**Comment by brendanheywood** [comment] 2017-08-13 23:35
hi @abias - yes we probably could and should be more forgiving in this plugin, but really you just have a corrupt moodle filesystem and this is going to show up in other places too. I'd suggest that your refresh script also does some proper cleanup of the moodle filesystem records so there are no dangling pointers to missing files. As an aside our data cleaner plugin handles this:

https://github.com/catalyst/moodle-local_datacleaner

Even without the full datacleaner you could probably get by with a 1 liner sql in your refresh script which deletes all mdl_files records for files over a certain size.

**Comment by mattporritt** [comment] 2017-08-15 02:26
Try as I might I can't reproduce this error. I can delete a file on the file system and when I run the index task I get PHP warnings but I can't get it to raise an error. The core PHP functions that Moodle calls `fopen` and `getimagesize` either return a warning or false. I've confirmed this  against the PHP docs.

I'm happy to put a try catch statement in to handle this, but I need a reproducable test case to do this.

@brendanheywood ideas?

**Comment by brendanheywood** [comment] 2017-08-15 03:28
@abias - it's possibly there is a chance there is some crufty data in your database related to the trashdir. It looks to me like it may be exploding after calling try_content_recovery(). This is all guess work without seeing some real files but perhaps the file is half deleted, and then it tries to index and then half restores it. Maybe poke around the trashdir and see if that makes any difference.

**Comment by abias** [comment] 2017-08-17 20:16
Thanks, Brendan and Matt, for your feedback.

First, I am aware of local_datacleaner and already has a look at it, but as we have a working reset solution for test- and dev-systems, I hesitated to replace it up to now as local_datacleaner has some challenges on its own.

Then, well, I have to admit that our moodledata filesystem may be called corrupt in our test- and dev-systems. Within the reset script, I am excluding /sessions, /trashdir, /temp, /cache, /localcache completely and all files > 50MB in /filedir.

Up to now, I have only run into a fatal error when opening a excluded file in Moodle, for example when opening a video which has been uploaded in a resource activity and is now missing on disk.

Matt, could you please check if you can reproduce the problem by emptying trashdir completely? If this also doesn't trigger the problem in your setup, the ticket can be closed and I will try to fix my reset stuff locally.

Thanks,
Alex

**Comment by brendanheywood** [comment] 2017-08-18 08:14
@abias I'd love to hear about your challenges / showstoppers for the datacleaner, please open issues over there even if they are just vague high level ideas so it's on our radar for later

In your reset script you should be able to easily search for all files over a 50mb, and then just replace their content hash with the known content hash of a existing small file in the site data. This way everything still kinda works and nothing is orphaned. eg:

https://github.com/catalyst/moodle-local_datacleaner/tree/master/cleaner/sitedata/fixtures

**Comment by mattporritt** [comment] 2017-08-20 06:11
I'm going to close this as I cannot reproduce the error. It'll be hard to change the code in any meaningful way without a reliable test case to reproduce.
If anyone can find a test case for this, we can revisit it.

**Closed by mattporritt** 2017-08-20 06:11 UTC
